### ISSUE TITLE
create download page

### ISSUE THREAD

**Issue by MohammadAlHabil** [GSG-FC03/cinema-app-8#4]
### Rules
1.Use the link of the Actor font in head tag ()
<link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Actor&display=swap" rel="stylesheet">

2. The title of website is cinema
3. Use semantic tag
4. put the colors in root
:root { --actionColor: #6644b8; 
--selectColor: #ff8fc6; 
--tagColor: #36274b;
 --fontColor: #ecbbda; 
--fontColor1: #bcb7c3; 
--divBackground: #210f37; 
--divBackground1: #200f37; 
--mainBackground: #17082a; 
--customColor: #f79e44; } 
5. Use flexbox 
6. Don't repeat the same code 
7. Make the website responsive 
8. Style the html code by CSS and let it mobile-first.

Write html file for a cinema web page
- [x]  - put the image of movie in header tag
- [x]  - add the name of movie in h1
- [x]  - make section for Quality contains the number of quality
- [x]  - make section for Voice acting contains the checkbox 
- [x]  - make button for download movie

- [x]  - Make it responsive so it will be suitable for screen with min-width 1023px.

Here is an image that describes all the previous tasks
![download](https://user-images.githubusercontent.com/58392811/123485246-63612b80-d612-11eb-9eb7-dba610609846.png)
hat contains

**Comment by sara219** [comment]
@MohammadAlHabil  
Describe the structure of the page and divide it into several tasks.
